- name: Add VSCode key
  apt_key:
    id: EB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

## SQLite3 is used to fix VSCode's default configuration file.
## By default, when it first starts it opens a browser window.

- name: Install VSCode
  apt:
    name: ['code', 'sqlite3']
    state: present
    update_cache: yes

- name: Create config folder
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.config/Code/Local Storage/"
    state: directory

 ##
 ## Set the 'workbench.hide.welcome' to 'true'
 ##
- name: Create database
  become: yes
  become_user: "{{ username }}"
  shell: |
          rm -f /home/{{ username }}/.config/Code/Local\ Storage/file__0.localstorage &&
          echo "
            PRAGMA foreign_keys=OFF;
            BEGIN TRANSACTION;
            CREATE TABLE ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB NOT NULL ON CONFLICT FAIL);
            INSERT INTO ItemTable VALUES('storage://global/workbench.hide.welcome',X'7400720075006500');
            COMMIT;
           .quit
          " | sqlite3 /home/{{ username }}/.config/Code/Local\ Storage/file__0.localstorage
