name: Publish labs
on:
  push:
    branches:
      - master
    paths:
      - 'labs/**'
jobs:
  publish_labs:
    runs-on: ubuntu-20.04
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive labs
        run: |
          ./scripts/labs-post-receive

      - name: Publish labs to elf
        uses: garygrossgarten/github-action-scp@release
        with:
          local: '/home/runner/res/current/laboratoare/'
          remote: 'res/current/laboratoare/'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
